export const propertiesMap = {
  name: 'Nome',
  type: 'Tipo',
  currencies: 'Moedas',
  siteUrl: 'Site',
  swiftCode: 'Código Swift',
  icon: 'Ícone',
  color: 'Cor',
  wishlistId: 'ID Lista de Desejos',
  incomeId: 'ID Renda',
  categoryId: 'ID Categoria',
  title: 'Título',
  description: 'Descrição',
  estimatedDate: 'Data Estimada',
  priority: 'Prioridade',
  recurrence: 'Recorrência',
  startDate: 'Data Inicial',
  endDate: 'Data Final',
  estimatedAmount: 'Montante Estimado',
  quantity: 'Quantidade',
  total: 'Total',
  prices: 'Preços',
  status: 'Estado',
  province: 'Província',
  city: 'Cidade',
  address: 'Endereço',
  coordinate: 'Coordenadas',
  latitude: 'Latitude',
  longitude: 'Longitude',
  expenseId: 'ID Despesa',
  amount: 'Montante',
  locationId: 'ID Local',
  contacts: 'Contactos',
  walletId: 'ID Carteira',
  duration: 'Duração',
  currency: 'Moeda',
  estimatedDateReceipt: 'Data Estimada de Recebimento',
  date: 'Data',
  incomes: 'Rendas',
  expenses: 'Despesas',
  totalAmount: 'Montante Total',
  note: 'Notas',
  email: 'Email',
  passwordHash: 'Hash Senha',
  providerId: 'ID Provedor',
  accountId: 'ID Conta',
  reference: 'Referência',
  iban: 'IBAN',
  details: 'Detalhes',
  active: 'Ativo',
  targetDate: '', // TODO Ver a tradução
  expectedLocationId: '', // TODO ver tradução,
  estimatedCost: 'Costo Estimado',
};
